// React/src/App.tsx
import React, {
  memo, useCallback, useEffect, useRef, useState,
} from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import DataGrid, { type DataGridTypes, type DataGridRef } from 'devextreme-react/data-grid';
import type dxDataGrid from 'devextreme/ui/data_grid';
import { customers } from './data';

interface SelectedRange {
  startRowIndex?: number;
  endRowIndex?: number;
  startColumnIndex?: number;
  endColumnIndex?: number;
}

interface CellInfo {
  cellElement: HTMLElement;
  rowIndex: number;
  columnIndex: number;
}

interface CellData {
  rowIndex: number;
  columnIndex: number;
}

let selectedRange: SelectedRange = {};
let shiftSelectRange: SelectedRange = {};
let isSelectionStopped = false;
const cellsInfo: CellInfo[] = [];

const columns = ['CompanyName', 'City', 'State', 'Phone', 'Fax'];

function App(): JSX.Element {
  const dataGrid = useRef<DataGridRef>(null);
  const [data, setData] = useState<CellData[]>([]);

  const foreachRange = useCallback(
    (range: SelectedRange, func: (rowIndex: number, columnIndex: number) => void): void => {
      const dataTemp: CellData[] = [];
      if (range.startRowIndex !== undefined && range.startRowIndex >= 0) {
        const minRowIndex = Math.min(
          range.startRowIndex,
          range.endRowIndex ?? range.startRowIndex,
        );
        const maxRowIndex = Math.max(
          range.startRowIndex,
          range.endRowIndex ?? range.startRowIndex,
        );
        const minColumnIndex = Math.min(
          range.startColumnIndex ?? 0,
          range.endColumnIndex ?? range.startColumnIndex ?? 0,
        );
        const maxColumnIndex = Math.max(
          range.startColumnIndex ?? 0,
          range.endColumnIndex ?? range.startColumnIndex ?? 0,
        );

        for (let rowIndex = minRowIndex; rowIndex <= maxRowIndex; rowIndex += 1) {
          for (
            let columnIndex = minColumnIndex;
            columnIndex <= maxColumnIndex;
            columnIndex += 1
          ) {
            func(rowIndex, columnIndex);
            dataTemp.push({ rowIndex, columnIndex });
          }
        }
      }
      setData(dataTemp);
    },
    [],
  );

  const showSelection = useCallback(
    (component: dxDataGrid, range: SelectedRange): void => {
      const selectedCells = component.element().querySelectorAll('.cell-selected');

      // Remove previously selected cells
      if (selectedCells) {
        for (const cell of selectedCells) {
          cell.classList.remove('cell-selected');
        }
      }

      // You can then get the cell's value here
      foreachRange(range, (rowIndex, columnIndex) => {
        const cellElement = component.getCellElement(rowIndex, columnIndex);
        if (cellElement) {
          cellElement.classList.add('cell-selected');
        }
      });
    },
    [foreachRange],
  );

  useEffect(() => {
    const gridInstance = dataGrid.current?.instance();
    if (!gridInstance) return;

    const dataGridElement = gridInstance.element();
    dataGridElement.addEventListener('touchmove', (args: TouchEvent) => {
      const event = args.touches[0];
      const element = document.elementFromPoint(
        event.clientX,
        event.clientY,
      ) as HTMLElement;
      const cellInfo = cellsInfo.filter((x) => x.cellElement === element)[0];
      if (cellInfo) {
        selectedRange.endRowIndex = cellInfo.rowIndex;
        selectedRange.endColumnIndex = cellInfo.columnIndex;
        showSelection(gridInstance, selectedRange);
      }
    });
  }, [showSelection]);

  const onCellHoverChanged = useCallback(
    (e: DataGridTypes.CellHoverChangedEvent): void => {
      const eventData = e as any;
      if (!eventData.event) return;
      const mouseEvent = eventData.event as MouseEvent;
      if (mouseEvent.buttons === 1) {
        if (isSelectionStopped) {
          isSelectionStopped = false;
          selectedRange = {};
        }

        if (selectedRange.startRowIndex === undefined) {
          selectedRange.startRowIndex = e.rowIndex;
        }

        if (selectedRange.startColumnIndex === undefined) {
          selectedRange.startColumnIndex = e.columnIndex;
        }

        selectedRange.endRowIndex = e.rowIndex;
        selectedRange.endColumnIndex = e.columnIndex;
        showSelection(e.component, selectedRange);
      } else {
        isSelectionStopped = true;
      }
    },
    [showSelection],
  );

  const onCellPrepared = useCallback(
    (e: DataGridTypes.CellPreparedEvent): void => {
      if (e.rowType === 'data' && e.cellElement) {
        cellsInfo.push({
          cellElement: e.cellElement,
          rowIndex: e.rowIndex,
          columnIndex: e.columnIndex,
        });

        e.cellElement.addEventListener('touchstart', () => {
          selectedRange.startRowIndex = e.rowIndex;
          selectedRange.endRowIndex = e.rowIndex;
          selectedRange.startColumnIndex = e.columnIndex;
          selectedRange.endColumnIndex = e.columnIndex;
          showSelection(e.component, selectedRange);
        });
      }
    },
    [showSelection],
  );

  const onCellClick = useCallback(
    (e: DataGridTypes.CellClickEvent): void => {
      if (e.rowType !== 'data') return;
      if (e.event && 'ctrlKey' in e.event && e.event.ctrlKey && 'shiftKey' in e.event && !e.event?.shiftKey) {
        // selects or deselects a single cell when Ctrl + Left Click
        if (e.cellElement && e.cellElement.classList.contains('cell-selected')) {
          setData((prevData) => prevData.filter(
            (item) => !(item.rowIndex === e.rowIndex && item.columnIndex === e.columnIndex),
          ));
          e.cellElement.classList.remove('cell-selected');
        } else {
          setData((prevData) => [
            ...prevData,
            { rowIndex: e.rowIndex, columnIndex: e.columnIndex },
          ]);
          if (e.cellElement) {
            e.cellElement.classList.add('cell-selected');
          }
        }
      } else if (
        e.event
        && 'ctrlKey' in e.event && !e.event.ctrlKey
        && 'shiftKey' in e.event && e.event.shiftKey
      ) {
        // Selection via Shift + Left Click
        shiftSelectRange.endRowIndex = e.rowIndex;
        shiftSelectRange.endColumnIndex = e.columnIndex;
        showSelection(e.component, shiftSelectRange);
      } else {
        shiftSelectRange.startRowIndex = e.rowIndex;
        shiftSelectRange.startColumnIndex = e.columnIndex;
        selectedRange.startRowIndex = e.rowIndex;
        selectedRange.endRowIndex = e.rowIndex;
        selectedRange.startColumnIndex = e.columnIndex;
        selectedRange.endColumnIndex = e.columnIndex;
        isSelectionStopped = false;
        showSelection(e.component, selectedRange);
      }
    },
    [showSelection],
  );

  const onContentReady = useCallback((): void => {
    setData([]);
  }, []);

  return (
    <React.Fragment>
      <DataGrid
        ref={dataGrid}
        id="gridContainer"
        dataSource={customers}
        keyExpr="ID"
        columns={columns}
        showBorders={true}
        onCellHoverChanged={onCellHoverChanged}
        onCellClick={onCellClick}
        onCellPrepared={onCellPrepared}
        onContentReady={onContentReady}
      />
      <h3 className="caption">Selected Cells:</h3>
      <div className="selected-data">
        <ul>
          {data.map((item, i) => {
            const gridInstance = dataGrid.current?.instance();
            if (!gridInstance) return null;
            return (
              <li key={i}>
                {gridInstance.cellValue(item.rowIndex, item.columnIndex)}
              </li>
            );
          })}
        </ul>
      </div>
    </React.Fragment>
  );
}

export default memo(App);

// Angular/src/app/app.component.ts
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { Customer, Service, CellInfo, SelectedRange } from './app.service';
import { DxDataGridComponent } from 'devextreme-angular';
import { CellHoverChangedEvent, CellClickEvent, CellPreparedEvent } from 'devextreme/ui/data_grid';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [Service],
})
export class AppComponent implements AfterViewInit{
  @ViewChild(DxDataGridComponent) dataGrid !: DxDataGridComponent;
  title = 'MultipleSelection';
  customers: Customer[];
  data: CellInfo[] = [];
  selectedRange:SelectedRange = {};
  shiftSelectRange: SelectedRange = {};
  isSelectionStopped!: boolean;
  cellInfos: CellInfo[] = [];
  constructor(service: Service) {
    this.customers = service.getCustomers();
  }

  foreachRange(selectedRange:any, func:Function) {
    this.data = [];
    if(selectedRange.startRowIndex >= 0) {
      const minRowIndex = Math.min(selectedRange.startRowIndex, selectedRange.endRowIndex);
      const maxRowIndex = Math.max(selectedRange.startRowIndex, selectedRange.endRowIndex);
      const minColumnIndex = Math.min(selectedRange.startColumnIndex, selectedRange.endColumnIndex);
      const maxColumnIndex = Math.max(selectedRange.startColumnIndex, selectedRange.endColumnIndex);
      
      for(let rowIndex = minRowIndex; rowIndex <= maxRowIndex; rowIndex++) {
        for(let columnIndex = minColumnIndex; columnIndex <= maxColumnIndex; columnIndex++) {
          func(rowIndex, columnIndex);
          this.data.push({rowIndex: rowIndex, columnIndex: columnIndex});
        }
      }
    }
  }

  getCellValue(info:any){
    return this.dataGrid.instance.cellValue(info.rowIndex, info.columnIndex);
  }

  showSelection(component:any, selectedRange:SelectedRange) {
    const selectedCells = component.element().querySelectorAll(".cell-selected");
    //Remove previously selected cells
    if(selectedCells){
      for(let i = 0; i < selectedCells.length; i++){
        selectedCells[i].classList.remove("cell-selected")
      }
    }
    //You can then get the cell's value here
    this.foreachRange(selectedRange, function(rowIndex:Number, columnIndex:Number) {
      component.getCellElement(rowIndex, columnIndex).classList.add("cell-selected");
    });
  }
  onCellPrepared(e: CellPreparedEvent){
    if(e.rowType === "data") this.cellInfos.push(
      {
        cellElement: e.cellElement,
        rowIndex: e.rowIndex,
        columnIndex: e.columnIndex,
      }
    );
    e.cellElement.addEventListener("touchstart", (args:any)=>{
        this.selectedRange.startRowIndex = this.selectedRange.endRowIndex = e.rowIndex;
        this.selectedRange.startColumnIndex = this.selectedRange.endColumnIndex = e.columnIndex;
        this.showSelection(e.component, this.selectedRange);
    })
  }
  onCellHoverChanged(e: any){
    const event = e.event;
      if(event.buttons === 1) {
        
      	if(this.isSelectionStopped) {
        	this.isSelectionStopped = false;
        	this.selectedRange = {};
        }
        if(this.selectedRange.startRowIndex === undefined) {
        	this.selectedRange.startRowIndex = e.rowIndex;
        }
        if(this.selectedRange.startColumnIndex === undefined) {
        	this.selectedRange.startColumnIndex = e.columnIndex;
        }
        
        this.selectedRange.endRowIndex = e.rowIndex;
      	this.selectedRange.endColumnIndex = e.columnIndex;
        
        this.showSelection(e.component, this.selectedRange);
        
      }
      else {
      	this.isSelectionStopped = true;
      }
  }

  ngAfterViewInit(){
    const dataGridElement = this.dataGrid.instance.element();
    dataGridElement.addEventListener("touchmove", (args:any)=>{
      const event=args.touches[0],
      element = document.elementFromPoint(event.clientX, event.clientY),
      cellInfo = this.cellInfos.filter((x:any)=>x.cellElement === element)[0];
      if(cellInfo){
        this.selectedRange.endRowIndex = cellInfo.rowIndex;
        this.selectedRange.endColumnIndex = cellInfo.columnIndex;
        this.showSelection(this.dataGrid.instance, this.selectedRange);  
      }
    });
  }

  onCellClick(e:CellClickEvent) { //Save the first hovered cell
    if (e.event && e.event.ctrlKey === true && e.event.shiftKey === false) { //selects or deselects a single cell when Ctrl + Left Click
      if (e.cellElement.classList.contains("cell-selected")) {
        this.data = this.data.filter((item:any) => !(item.rowIndex === e.rowIndex && item.columnIndex === e.columnIndex));
        e.cellElement.classList.remove("cell-selected");
      } else {
        this.data.push({rowIndex: e.rowIndex, columnIndex: e.columnIndex})
        e.cellElement.classList.add("cell-selected");
      }
    }
    else if(e.event && e.event.ctrlKey === false && e.event.shiftKey === true){ //Selection via Shift + Left Click
      
      this.shiftSelectRange.endRowIndex = e.rowIndex;
      this.shiftSelectRange.endColumnIndex = e.columnIndex;
      this.showSelection(e.component, this.shiftSelectRange);
      
    }
    else{
      this.shiftSelectRange.startRowIndex = e.rowIndex;
      this.shiftSelectRange.startColumnIndex = e.columnIndex;
      this.selectedRange.startRowIndex = this.selectedRange.endRowIndex = e.rowIndex;
      this.selectedRange.startColumnIndex = this.selectedRange.endColumnIndex = e.columnIndex;
      this.isSelectionStopped = false;
      this.showSelection(e.component, this.selectedRange);
    }
    
  }
}

<dx-data-grid
  id="gridContainer"
  [dataSource]="customers"
  keyExpr="ID"
  [columns]="['CompanyName', 'City', 'State', 'Phone', 'Fax']"
  [showBorders]="true"
  (onCellHoverChanged) = "onCellHoverChanged($event)"
  (onCellClick) = "onCellClick($event)"
  (onCellPrepared) = "onCellPrepared($event)"
>
</dx-data-grid>
<div class="selected-data">
  <h3 class="caption">Selected Cells:</h3>

  <ul>
    <li *ngFor='let info of data'>{{ getCellValue(info) }}</li>
  </ul>
</div>
